const SEQUELIZE = "SEQUELIZE";
const USERS_REPOSITORY = "USERS_REPOSITORY";
const ADMIN_REPOSITORY = "ADMIN_REPOSITORY";
const ROLE_REPOSITORY = "ROLE_REPOSITORY";
const QUESTIONS_REPOSITORY = "QUESTIONS_REPOSITORY";

export {
  SEQUELIZE,
  USERS_REPOSITORY,
  ADMIN_REPOSITORY,
  ROLE_REPOSITORY,
  QUESTIONS_REPOSITORY
}
;
