const SEQUELIZE = "SEQUELIZE";
const USERS_REPOSITORY = "USERS_REPOSITORY";
const ADMIN_REPOSITORY = "ADMIN_REPOSITORY";
const ROLE_REPOSITORY = "ROLE_REPOSITORY";
const QUESTIONS_REPOSITORY = "QUESTIONS_REPOSITORY";
const ATTEMPTS_REPOSITORY = "ATTEMPTS_REPOSITORY";

export {
  SEQUELIZE,
  USERS_REPOSITORY,
  ADMIN_REPOSITORY,
  ROLE_REPOSITORY,
  QUESTIONS_REPOSITORY,
  ATTEMPTS_REPOSITORY
}
;
